### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'pylint'

### ISSUE THREAD

**Issue by ExcaliburZero** [ExcaliburZero/jekyll-helper#3]
The following issue is showing up in Travis CI.

```
======================================================================
ERROR: run pylint in error only mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ExcaliburZero/jekyll-helper/tests/test_lint.py", line 16, in test_project_errors_only
    return_code = subprocess.call(["pylint", '-E', 'jekyll_helper'])
  File "/opt/python/3.2.5/lib/python3.2/subprocess.py", line 470, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/opt/python/3.2.5/lib/python3.2/subprocess.py", line 744, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.2.5/lib/python3.2/subprocess.py", line 1394, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'pylint'
```

**Comment by ExcaliburZero** [comment]
This issue is currently only being thrown by Python 3.2, and not by 2.7.

**Python 3.2**

```
======================================================================
ERROR: run pylint in error only mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ExcaliburZero/jekyll-helper/tests/test_lint.py", line 16, in test_project_errors_only
    return_code = subprocess.call(["pylint", '-E', 'jekyll_helper'])
  File "/usr/lib/python3.2/subprocess.py", line 471, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python3.2/subprocess.py", line 745, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.2/subprocess.py", line 1361, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'pylint'
```

**Comment by ExcaliburZero** [comment]
However, Python 2.7 is throwing a somewhat similar error.

**Python 2.7**

```
======================================================================
ERROR: run pylint in error only mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ExcaliburZero/jekyll-helper/tests/test_lint.py", line 16, in test_project_errors_only
    return_code = subprocess.call(["pylint", '-E', 'jekyll_helper'])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ExcaliburZero** [comment]
I tried running the command `pylint -E jekyll_helper` on my local system, and it noted that I needed to install pylint in order to be able to run it. So I added pylint to the Travis CI config apt-get install line.

**Comment by ExcaliburZero** [comment]
The addition of pylint to the apt-get line seems to have gotten rid of the error in both Python 3.2 and 2.7.
