### ISSUE TITLE
RuntimeError: Gtk couldn't be initialized

### ISSUE THREAD

**Issue by ExcaliburZero** [ExcaliburZero/jekyll-helper#5]
The following errors resulted from the Travis CI tests using Python 2.7 and Python 3.2:

**Python 2.7**

```
======================================================================
ERROR: Failure: RuntimeError (Gtk couldn't be initialized)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/ExcaliburZero/jekyll-helper/jekyll_helper/__init__.py", line 10, in <module>
    from gi.repository import Gtk # pylint: disable=E0611
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 76, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 224, in _load
    overrides_modules = __import__('gi.overrides', fromlist=[self._namespace])
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1533, in <module>
    raise RuntimeError("Gtk couldn't be initialized")
RuntimeError: Gtk couldn't be initialized
```

**Python 3.2**

```
======================================================================
ERROR: Failure: RuntimeError (Gtk couldn't be initialized)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/ExcaliburZero/jekyll-helper/jekyll_helper/__init__.py", line 10, in <module>
    from gi.repository import Gtk # pylint: disable=E0611
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 76, in load_module
    dynamic_module._load()
  File "/usr/lib/python3/dist-packages/gi/module.py", line 224, in _load
    overrides_modules = __import__('gi.overrides', fromlist=[self._namespace])
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1533, in <module>
    raise RuntimeError("Gtk couldn't be initialized")
RuntimeError: Gtk couldn't be initialized
```

**Comment by ExcaliburZero** [comment]
These  pages seems to be relevant:
- [python "module gi.repository is missing" (catfish 0.4.0.2 for Xfce's Thunar) ](http://www.linuxquestions.org/questions/slackware-14/python-module-gi-repository-is-missing-catfish-0-4-0-2-for-xfce%27s-thunar-4175437749/)
- [Can't import gi.repository modules](https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=59832)

**Comment by ExcaliburZero** [comment]
I was able to stop the error by following the directions here:
- http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29
