### ISSUE TITLE
SyntaxError: invalid syntax "except OSError, e:"

### ISSUE THREAD

**Issue by ExcaliburZero** [ExcaliburZero/jekyll-helper#7]
The following error appears twice in the Travis CI test with Python 3.2, but not with 2.7.

**Python 3.2**

```
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (JekyllHelperWindow.py, line 33))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/ExcaliburZero/jekyll-helper/jekyll_helper/__init__.py", line 12, in <module>
    from jekyll_helper import JekyllHelperWindow
  File "/home/travis/build/ExcaliburZero/jekyll-helper/jekyll_helper/JekyllHelperWindow.py", line 33
    except OSError, e:
                  ^
SyntaxError: invalid syntax
```

**Comment by ExcaliburZero** [comment]
It looks like Python 3 versions require except statements to use the word `as` instead of a comma. See the following page:
- https://docs.python.org/2/tutorial/errors.html

**Comment by ExcaliburZero** [comment]
I changed all of the commas in except statements and that seems to have fixed the errors.
